### ISSUE TITLE
از کار افتادن برنامه

### ISSUE THREAD

**Issue by sacanebrahimirad** [Vauth/vox#15]
برنامه به طور کامل از کار افتاده

**Comment by Vauth** [comment]
### Depending on your `ISP` and current restrictions in **your area**, The app may **not** work.
- Try using different ISPs like `Irancell`

### Test Result (5/26/2024):
![image](https://github.com/Vauth/vox/assets/122077080/c156643c-1b4d-4dfd-b8ee-1351a8e25d6e)
