### ISSUE TITLE
doesn't work with http://socks= and CFON Mode on (default settings)

### ISSUE THREAD

**Issue by paulvek** [Vauth/vox#7]
thank you first, I used the Windows .exe release. it works great with fast speed but not by default settings!
I tested first with CFON mode on and scan mode off and country select automatic and warp key empty and default port, not work in this situation.
but when CFON Mode is off ScanMode is on and the warp key is empty and with the default port, works great in this situation.
![Screenshot 2024-04-23 144956](https://github.com/Vauth/vox/assets/153482922/8852b23b-2b0b-49c6-89c5-5ac346c7ae6f)
after clicking the connect button windows proxy automatically on but the proxy address like this http://socks=127.0.0.1 - doesn't work with this, I removed http://socks= from first and just added proxy 127.0.0.1 And it is in this situation that everything works perfectly and without problems. It's like a spell!
![Screenshot 2024-04-23 145200](https://github.com/Vauth/vox/assets/153482922/912b8dc2-648d-4e2d-b530-6b33d158e675)

**Comment by Vauth** [comment]
‼️ Check out the new [release](https://github.com/Vauth/vox/releases/tag/v1.1), if the issue has been resolved.

**Comment by paulvek** [comment]
> ‼️ Check out the new [release](https://github.com/Vauth/vox/releases/tag/v1.1), if the issue has been resolved.

thanks @Vauth. I checked. but Windows 11 detects the new release of this app as a trojan! there it not a problem?

![trojan](https://github.com/Vauth/vox/assets/153482922/becdd8dd-9b43-4773-ad19-f70af2f77eeb)

**Comment by Vauth** [comment]
> > ‼️ Check out the new [release](https://github.com/Vauth/vox/releases/tag/v1.1), if the issue has been resolved.
> 
> thanks @Vauth. I checked. but Windows 11 detects the new release of this app as a trojan! there it not a problem?
> 
> ![trojan](https://private-user-images.githubusercontent.com/153482922/324852909-becdd8dd-9b43-4773-ad19-f70af2f77eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Nzk1OTksIm5iZiI6MTcxMzg3OTI5OSwicGF0aCI6Ii8xNTM0ODI5MjIvMzI0ODUyOTA5LWJlY2RkOGRkLTliNDMtNDc3My1hZDE5LWY3MGFmMmY3N2VlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMzM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQzNzMxOTkxZGIyODhlYjAzMDIyMWI1NDg3MTRkZmZiNzA0ZTNiYjljNjIxMDQ4MWYzNTVhNTE0OTM2ZjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cY7FU3DHwnw4si3cVEAkBqMMJIiiCpVWIsph1VtU3Nw)

There might be a problem with signing the exe (from github), for now simply pass it by clicking `Allow on device` .

**Comment by paulvek** [comment]
> > > ‼️ Check out the new [release](https://github.com/Vauth/vox/releases/tag/v1.1), if the issue has been resolved.
> > 
> > 
> > thanks @Vauth. I checked. but Windows 11 detects the new release of this app as a trojan! there it not a problem?
> > ![trojan](https://private-user-images.githubusercontent.com/153482922/324852909-becdd8dd-9b43-4773-ad19-f70af2f77eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Nzk1OTksIm5iZiI6MTcxMzg3OTI5OSwicGF0aCI6Ii8xNTM0ODI5MjIvMzI0ODUyOTA5LWJlY2RkOGRkLTliNDMtNDc3My1hZDE5LWY3MGFmMmY3N2VlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMzM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQzNzMxOTkxZGIyODhlYjAzMDIyMWI1NDg3MTRkZmZiNzA0ZTNiYjljNjIxMDQ4MWYzNTVhNTE0OTM2ZjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cY7FU3DHwnw4si3cVEAkBqMMJIiiCpVWIsph1VtU3Nw)
> 
> There might be a problem with signing the exe (from github), for now simply pass it by clicking `Allow on device` .

Yes, I know how to get through it. But I am afraid that it has a security problem!

**Comment by Vauth** [comment]
> > > > ‼️ Check out the new [release](https://github.com/Vauth/vox/releases/tag/v1.1), if the issue has been resolved.
> > > 
> > > 
> > > thanks @Vauth. I checked. but Windows 11 detects the new release of this app as a trojan! there it not a problem?
> > > ![trojan](https://private-user-images.githubusercontent.com/153482922/324852909-becdd8dd-9b43-4773-ad19-f70af2f77eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Nzk1OTksIm5iZiI6MTcxMzg3OTI5OSwicGF0aCI6Ii8xNTM0ODI5MjIvMzI0ODUyOTA5LWJlY2RkOGRkLTliNDMtNDc3My1hZDE5LWY3MGFmMmY3N2VlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMzM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQzNzMxOTkxZGIyODhlYjAzMDIyMWI1NDg3MTRkZmZiNzA0ZTNiYjljNjIxMDQ4MWYzNTVhNTE0OTM2ZjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cY7FU3DHwnw4si3cVEAkBqMMJIiiCpVWIsph1VtU3Nw)
> > 
> > 
> > There might be a problem with signing the exe (from github), for now simply pass it by clicking `Allow on device` .
> 
> Yes, I know how to get through it. But I am afraid that it has a security problem!

Well as the developer, I can't tell you that its safe (because you may not believe), But its open source :)
You have 2 choices:
- Check source code if you have enough knowledge
- Or ask an expert to do it

Good luck with that :)

**Comment by paulvek** [comment]
> > > > > ‼️ Check out the new [release](https://github.com/Vauth/vox/releases/tag/v1.1), if the issue has been resolved.
> > > > 
> > > > 
> > > > thanks @Vauth. I checked. but Windows 11 detects the new release of this app as a trojan! there it not a problem?
> > > > ![trojan](https://private-user-images.githubusercontent.com/153482922/324852909-becdd8dd-9b43-4773-ad19-f70af2f77eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Nzk1OTksIm5iZiI6MTcxMzg3OTI5OSwicGF0aCI6Ii8xNTM0ODI5MjIvMzI0ODUyOTA5LWJlY2RkOGRkLTliNDMtNDc3My1hZDE5LWY3MGFmMmY3N2VlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMzM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQzNzMxOTkxZGIyODhlYjAzMDIyMWI1NDg3MTRkZmZiNzA0ZTNiYjljNjIxMDQ4MWYzNTVhNTE0OTM2ZjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cY7FU3DHwnw4si3cVEAkBqMMJIiiCpVWIsph1VtU3Nw)
> > > 
> > > 
> > > There might be a problem with signing the exe (from github), for now simply pass it by clicking `Allow on device` .
> > 
> > 
> > Yes, I know how to get through it. But I am afraid that it has a security problem!
> 
> Well as the developer, I can't tell you that its safe (because you may not believe), But its open source :) You have 2 choices:
> 
> * Check source code if you have enough knowledge
> * Or ask an expert to do it
> 
> Good luck with that :)

**In any case, you solved the reported problem about the proxy completely, and now after connecting, we don't need to go and update something manually, and it can be easily connected and usable.**

I don't have enough knowledge about security programming I just reported a problem I observed to you as a normal user.

**Comment by Vauth** [comment]
> > > > > > ‼️ Check out the new [release](https://github.com/Vauth/vox/releases/tag/v1.1), if the issue has been resolved.
> > > > > 
> > > > > 
> > > > > thanks @Vauth. I checked. but Windows 11 detects the new release of this app as a trojan! there it not a problem?
> > > > > ![trojan](https://private-user-images.githubusercontent.com/153482922/324852909-becdd8dd-9b43-4773-ad19-f70af2f77eeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4Nzk1OTksIm5iZiI6MTcxMzg3OTI5OSwicGF0aCI6Ii8xNTM0ODI5MjIvMzI0ODUyOTA5LWJlY2RkOGRkLTliNDMtNDc3My1hZDE5LWY3MGFmMmY3N2VlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QxMzM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGQzNzMxOTkxZGIyODhlYjAzMDIyMWI1NDg3MTRkZmZiNzA0ZTNiYjljNjIxMDQ4MWYzNTVhNTE0OTM2ZjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cY7FU3DHwnw4si3cVEAkBqMMJIiiCpVWIsph1VtU3Nw)
> > > > 
> > > > 
> > > > There might be a problem with signing the exe (from github), for now simply pass it by clicking `Allow on device` .
> > > 
> > > 
> > > Yes, I know how to get through it. But I am afraid that it has a security problem!
> > 
> > 
> > Well as the developer, I can't tell you that its safe (because you may not believe), But its open source :) You have 2 choices:
> > 
> > * Check source code if you have enough knowledge
> > * Or ask an expert to do it
> > 
> > Good luck with that :)
> 
> **In any case, you solved the reported problem about the proxy completely, and now after connecting, we don't need to go and update something manually, and it can be easily connected and usable.**
> 
> I don't have enough knowledge about security programming I just reported a problem I observed to you as a normal user.

Appreciate that. If you faced any further issue, feel free to report.
