### ISSUE TITLE
Problem opening some sites

### ISSUE THREAD

**Issue by paulvek** [Vauth/vox#9]
Most of the sites are opened without any problem, especially accessing YouTube, which is filtered in our country, is very easy, without restrictions, and great with this app.
But it seems that access to some sites is not possible. For example, gemini.google.com
![gemini](https://github.com/Vauth/vox/assets/153482922/bb732bf4-5aaf-41ae-bdbb-d035b5986163)

In your opinion, what is the reason for this problem and what is the solution? Can you fix it?
As an additional explanation, I say that Gemini is not a filter like YouTube, Gemini has sanctioned our country. However, I can access it with other VPNs and unsanctioned DNS, but it is not possible to access it with your software.
Why do you think this is so? Because there shouldn't be any problem and sites like YouTube, which also have restrictions, can be accessed.

**Comment by Vauth** [comment]
### Solutions may work:
- Set [Proxy DNS for Browser](https://github.com/Vauth/vox?tab=readme-ov-file#-proxy-dns-for-browsers) **(for the best performance, its required)**
- Turn on CFON & set it on USA **(an unrestricted country)**

**Note:** as you may know without CFON on, warp will handle the connection (which may not work on some websites)

**Comment by sacanebrahimirad** [comment]
I set proxy correctly but since I updated to version2 , i get EOF error

**Comment by paulvek** [comment]
> ### Solutions may work:
> * Set [Proxy DNS for Browser](https://github.com/Vauth/vox?tab=readme-ov-file#-proxy-dns-for-browsers) **(for the best performance, its required)**
> * Turn on CFON & set it on USA **(an unrestricted country)**
> 
> **Note:** as you may know without CFON on, warp will handle the connection (which may not work on some websites)

if CFON on , doesn't work for me. as I Sayed in this topic: https://github.com/Vauth/vox/issues/7

**Comment by Vauth** [comment]
Can you provide more details?

**Comment by paulvek** [comment]
> Can you provide more details?

I tested CFON on option with USA country but not any difference in results and I not be connect and use them.
and I don't catch it (Turn on CFON & set it on USA (an unrestricted country) Are proxy settings not the same as Windows settings in Chrome? There is no separate section in Chrome for this! And do I need to set/change anything in terms of accessibility? Because your program does this automatically.
I can only connect this way
https://github.com/Vauth/vox/issues/7
But this method cannot open some sites (can't open all sites) and only some of them are available.
thank you for support

**Comment by Vauth** [comment]
Well the first option is required ( [Set Proxy DNS for Browser](https://github.com/Vauth/vox?tab=readme-ov-file#-proxy-dns-for-browsers)) .
This section is available on FireFox & Tor.
You have to search about chrome if it supports that option.

- Proxy DNS for Browser avoids data leaks

**Comment by paulvek** [comment]
> Well the first option is required ( [Set Proxy DNS for Browser](https://github.com/Vauth/vox?tab=readme-ov-file#-proxy-dns-for-browsers)) . This section is available on FireFox & Tor. You have to search about chrome if it supports that option.
> 
> * Proxy DNS for Browser avoids data leaks

thank you. I tested this

![mozilla](https://github.com/Vauth/vox/assets/153482922/66cb1b81-c303-46cd-90e2-3077978b8b00)
![fire](https://github.com/Vauth/vox/assets/153482922/23c9ddc6-d82e-49a7-b9e2-f1b4fb79bd1a)

but for now, Access to sites that were previously possible with that previous method (CFON off) is not possible.

![mozilla2](https://github.com/Vauth/vox/assets/153482922/d3c96116-a302-4a06-9312-ef91699f56aa)

**Comment by Vauth** [comment]
> > Well the first option is required ( [Set Proxy DNS for Browser](https://github.com/Vauth/vox?tab=readme-ov-file#-proxy-dns-for-browsers)) . This section is available on FireFox & Tor. You have to search about chrome if it supports that option.
> > 
> > * Proxy DNS for Browser avoids data leaks
> 
> thank you. I tested this
> 
> ![mozilla](https://private-user-images.githubusercontent.com/153482922/326164701-66cb1b81-c303-46cd-90e2-3077978b8b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDgyMzAsIm5iZiI6MTcxNDIwNzkzMCwicGF0aCI6Ii8xNTM0ODI5MjIvMzI2MTY0NzAxLTY2Y2IxYjgxLWMzMDMtNDZjZC05MGUyLTMwNzc5NzhiOGIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwODUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDhkODg3NmI1MGEzZWEyNWYwZWY5ZjdlYzZkNmRhNTMzMWY4NzgxZGI0OTE5ZGEyNThhNGFjZmQzYWUyZjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hfcp7BvScTgr8F_jwqZ0aUIM8VPAmIVPyz0Yii1jiyw) ![fire](https://private-user-images.githubusercontent.com/153482922/326165305-23c9ddc6-d82e-49a7-b9e2-f1b4fb79bd1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDgyMzAsIm5iZiI6MTcxNDIwNzkzMCwicGF0aCI6Ii8xNTM0ODI5MjIvMzI2MTY1MzA1LTIzYzlkZGM2LWQ4MmUtNDlhNy1iOWUyLWYxYjRmYjc5YmQxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwODUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTI5YzY4ZDE5ZDQxYzczMzk2MjU0MTc0N2M4ODUyOWEwNTJjYmRiNWYzZjA3Y2NiMTE3N2RlMDJjYTM4ZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AjI-X_-kNwLFPPXM5bS7bqLJyZsFHbEXxTCp41q6jh8)
> 
> but for now, Access to sites that were previously possible with that previous method (CFON off) is not possible.
> 
> ![mozilla2](https://private-user-images.githubusercontent.com/153482922/326164803-d3c96116-a302-4a06-9312-ef91699f56aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDgyMzAsIm5iZiI6MTcxNDIwNzkzMCwicGF0aCI6Ii8xNTM0ODI5MjIvMzI2MTY0ODAzLWQzYzk2MTE2LWEzMDItNGEwNi05MzEyLWVmOTE2OTlmNTZhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwODUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDc2ZjQzM2UyZjliYTdjNWZiMzg2ZDc5YjFjNzAxNWJkMjc2MTVhMzAwNjNjOWU0NjNjOTJiMTg0NjlkNzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pHWYwnLeBcUMUF6x3L4eOKgV9m8PBNFwsdB9gtU0JOU)

Weird, can you try this method with older version
I've tried `v1.0` on a virtual `windows 11 latest`. it worked fine.

If you still faced problem, 🤷  i have no idea (although its an experimental project)

**Comment by paulvek** [comment]
> > > Well the first option is required ( [Set Proxy DNS for Browser](https://github.com/Vauth/vox?tab=readme-ov-file#-proxy-dns-for-browsers)) . This section is available on FireFox & Tor. You have to search about chrome if it supports that option.
> > > 
> > > * Proxy DNS for Browser avoids data leaks
> > 
> > 
> > thank you. I tested this
> > ![mozilla](https://private-user-images.githubusercontent.com/153482922/326164701-66cb1b81-c303-46cd-90e2-3077978b8b00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDgyMzAsIm5iZiI6MTcxNDIwNzkzMCwicGF0aCI6Ii8xNTM0ODI5MjIvMzI2MTY0NzAxLTY2Y2IxYjgxLWMzMDMtNDZjZC05MGUyLTMwNzc5NzhiOGIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwODUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDhkODg3NmI1MGEzZWEyNWYwZWY5ZjdlYzZkNmRhNTMzMWY4NzgxZGI0OTE5ZGEyNThhNGFjZmQzYWUyZjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Hfcp7BvScTgr8F_jwqZ0aUIM8VPAmIVPyz0Yii1jiyw) ![fire](https://private-user-images.githubusercontent.com/153482922/326165305-23c9ddc6-d82e-49a7-b9e2-f1b4fb79bd1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDgyMzAsIm5iZiI6MTcxNDIwNzkzMCwicGF0aCI6Ii8xNTM0ODI5MjIvMzI2MTY1MzA1LTIzYzlkZGM2LWQ4MmUtNDlhNy1iOWUyLWYxYjRmYjc5YmQxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwODUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTI5YzY4ZDE5ZDQxYzczMzk2MjU0MTc0N2M4ODUyOWEwNTJjYmRiNWYzZjA3Y2NiMTE3N2RlMDJjYTM4ZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AjI-X_-kNwLFPPXM5bS7bqLJyZsFHbEXxTCp41q6jh8)
> > but for now, Access to sites that were previously possible with that previous method (CFON off) is not possible.
> > ![mozilla2](https://private-user-images.githubusercontent.com/153482922/326164803-d3c96116-a302-4a06-9312-ef91699f56aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDgyMzAsIm5iZiI6MTcxNDIwNzkzMCwicGF0aCI6Ii8xNTM0ODI5MjIvMzI2MTY0ODAzLWQzYzk2MTE2LWEzMDItNGEwNi05MzEyLWVmOTE2OTlmNTZhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwODUyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDc2ZjQzM2UyZjliYTdjNWZiMzg2ZDc5YjFjNzAxNWJkMjc2MTVhMzAwNjNjOWU0NjNjOTJiMTg0NjlkNzRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pHWYwnLeBcUMUF6x3L4eOKgV9m8PBNFwsdB9gtU0JOU)
> 
> Weird, can you try this method with older version I've tried `v1.0` on a virtual `windows 11 latest`. it worked fine.
> 
> If you still faced problem, 🤷 i have no idea (although its an experimental project)

I tested before version (version 1) and works well.
Now disabling cFON works with Chrome, but not all sites open this way.
And turning on cFON with the US country and Mozilla's specific settings opens all sites, but this is only possible in Tor and Firefox.
Now we have things in every browser and we lose things. We hope that there will be a comprehensive solution that is appropriate and compatible with all browsers and the tunnel to the entire system. good luck.

**Comment by Vauth** [comment]
We don't have any plan to upgrade the project to the next phase yet, Cuz the existence of this project is due to lack of oblivion's windows version, now that they're working on it, it's already enough.
